version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-spark
    environment:
      - "TZ=Etc/UTC"
      - "POSTGRES_USER=spark"
      - "POSTGRES_PASSWORD=spark"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"